trigger:
  branches:
    include:
    - master
  tags:
    include:
    - '*'
pr:
  - master
  
pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Debug'

steps:
- task: UseDotNet@2
  displayName: Use dotnet core SDK
  inputs:
    packageType: 'sdk'
    version: '3.0.x'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: |
      **/generator.csproj
      **/generator.tool.csproj
    arguments: '--configuration $(buildConfiguration)' # Update this to match your need
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      dotnet tool install GitVersion.Tool --tool-path .local-tools
      VERSION=$(.local-tools/dotnet-gitversion /output json /showvariable SemVer)
      dotnet pack --configuration $(buildConfiguration) -p:PackageVersion=$VERSION -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -o $(Build.ArtifactStagingDirectory)/nuget
    failOnStderr: true
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/nuget' 
    artifactName: 'nugets' 
    #publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    #parallel: false # Optional
    #parallelCount: # Optional
