# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  version: 0.1.0

steps:
- task: UseDotNet@2
  displayName: Use dotnet core SDK
  inputs:
    packageType: 'sdk'
    version: '3.0.x'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration Release' # Update this to match your need
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- script: dotnet pack **/generator.tool.csproj /p:PackageVersion=$(version) -o $(Build.ArtifactStagingDirectory)/nuget
- script: dotnet pack **/generator.csproj /p:PackageVersion=$(version) -o $(Build.ArtifactStagingDirectory)/nuget

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/nuget' 
    artifactName: 'nugets' 
    #publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    #parallel: false # Optional
    #parallelCount: # Optional
